services:
  db:
    extends:
      file: docker-compose.mysql.yml
      service: mysql_server
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -p -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  app:
    extends:
      file: docker-compose.app.yml
      service: petclinic_app
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      MYSQL_URL: jdbc:mysql://db:3306/petclinic
    depends_on:
      db:
        condition: service_healthy
        #condition: service_completed_successfully
    restart: unless-stopped

volumes:
  '.container_data_mysql':
