services:
  mysql_server:
    image: mysql:latest
    restart: always
    environment:
      #MYSQL_DATABASE: 'db' # database wil be created using schema.sql script
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: '@adm!n'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '@adm!n'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '13306:3306'
    expose:
      # Opens port 3306 on the container
      - '13306'
      # Where our data will be persisted
    volumes:
      - ./.container_data_mysql:/var/lib/mysql
      - ./mysql_scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
