scrape_configs:
  - job_name: 'PetClinicMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:15000']
        labels:
          application: 'Pet Clinic'
